# Generated by Django 4.2 on 2025-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('Qualification', models.CharField(max_length=500)),
                ('Experience', models.EmailField(default=None, max_length=254)),
                ('display_picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
