# Generated by Django 4.2 on 2025-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_doctor_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.IntegerField(),
        ),
    ]
