# Generated by Django 4.2 on 2025-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
