# Generated by Django 4.2 on 2025-02-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
