const doctorsData = [
    {
      id: 1,
      image: "https://tse1.mm.bing.net/th?id=OIP.-Ef7I-PGJPcy-P5bPKAe2AAAAA&pid=Api&P=0&h=220",
      name: "Dr. John Doe",
      qualifications: "MBBS, MD",
      experience: 10,
      department: "Cardiology",
    },
    {
      id: 2,
      image: "https://tse3.mm.bing.net/th?id=OIP.RWEutLK2BmQGwaFNIkDQEAHaHo&pid=Api&P=0&h=220",
      name: "Dr. Jane Smith",
      qualifications: "MBBS, MS",
      experience: 8,
      department: "Neurology",
    },
    {
      id: 3,
      image: "https://tse1.mm.bing.net/th?id=OIP.ztEdU8MqoMizCfjTbpjg8QHaJA&pid=Api&P=0&h=220",
      name: "Dr. Sam Wilson",
      qualifications: "BDS, MDS",
      experience: 5,
      department: "Dentistry",
    },
    {
      id: 4,
      image: "https://tse2.mm.bing.net/th?id=OIP.TV1iZqBVANz9XlBm2Y0oBwHaJ7&pid=Api&P=0&h=220",
      name: "Dr. Susan Brown",
      qualifications: "MBBS, DGO",
      experience: 12,
      department: "Gynecology",
    },
    {
      id: 5,
      image: "https://tse3.mm.bing.net/th?id=OIP.7D-C4nLp5MGX-4J1xAXgywHaK4&pid=Api&P=0&h=220",
      name: "Dr. Mike Taylor",
      qualifications: "MBBS, MS Ortho",
      experience: 7,
      department: "Orthopedics",
    },
    {
      id: 6,
      image: "https://tse4.mm.bing.net/th?id=OIP.WZuFeD-_Btx-rRmknaI_9AHaHa&pid=Api&P=0&h=220",
      name: "Dr. Emma Green",
      qualifications: "MBBS, MD",
      experience: 9,
      department: "Pediatrics",
    },
    {
      id: 7,
      image: "https://tse1.mm.bing.net/th?id=OIP.LLSPpDD0z3uBI6VzdrWyKgHaHY&pid=Api&P=0&h=220",
      name: "Dr. Liam Davis",
      qualifications: "MBBS, MD",
      experience: 11,
      department: "Radiology",
    },
    {
      id: 8,
      image: "https://tse3.mm.bing.net/th?id=OIP.8S0mx3EWEAKkOTi0mIpIgQHaLG&pid=Api&P=0&h=220",
      name: "Dr. Olivia White",
      qualifications: "MBBS, MS",
      experience: 6,
      department: "Dermatology",
    },
    {
      id: 9,
      image: "https://tse4.mm.bing.net/th?id=OIP.vPSChrtt4IjmB4AXCl6TbwAAAA&pid=Api&P=0&h=220",
      name: "Dr. Ethan Harris",
      qualifications: "MBBS, MS ENT",
      experience: 15,
      department: "ENT",
    },
  ];
  
  export default doctorsData;
  